### ISSUE TITLE
If empty string in AddWorkspace path, VisualStates unexpectedly exits

### ISSUE THREAD

**Issue by pushkalkatara** [JdeRobot/VisualStates#95]
If empty string is provided in the path, then visualstates shutdowns with the following error -

```
Traceback (most recent call last):
  File "/home/pushkalkatara/catkin/src/VisualStates/src/visualstates/gui/dialogs/workspacetab.py", line 75, in addWorkspace
    if self.isValidWorkspace(newDir):
  File "/home/pushkalkatara/catkin/src/VisualStates/src/visualstates/gui/dialogs/workspacetab.py", line 85, in isValidWorkspace
    files = os.listdir(dir)
OSError: [Errno 2] No such file or directory: ''
[1]    15434 abort (core dumped)  rosrun visualstates main.py
```

**Comment by sudo-panda** [comment]
Do we need to show the "This is not a catkin workspace ..." warning or just exit the dialog?

**Comment by pushkalkatara** [comment]
Hi @sudo-panda , maybe you can update the text in the dialog with "This is not catkin workspace or path not found".
